### ISSUE TITLE
Possible typo in Chapter 10?

### ISSUE THREAD

**Issue by edisons3608** [NUstat/intro-stat-data-sci#10]
"Recall that the critical values for 99%, 95%, and 90% confidence intervals for the 
 are given by 
and 
 respectively. These are likely numbers you will memorize from using frequently, but they can also be calculated using the **rnorm**() function in R.

qnorm(.005) #99% (i.e. 0.5% in each tail)

[1] -2.58
qnorm(.025) #95% (i.e. 2.5% in each tail)

[1] -1.96
qnorm(.05) #90% (i.e. 5% in each tail)

[1] -1.64"

Given the context, I think "rnorm()" was a typo for "qnorm()".

**Comment by akuyper** [comment]
Thank you.

**Comment by akuyper** [comment]
Thank you. It has been updated
